-- =====================================================================
-- 02_setup_roles_grants.sql
-- =====================================================================
-- Three role hierarchy mirrors a real hospital:
--   ANALYST_ROLE        — sees only de-identified data
--   CLINICIAN_ROLE      — sees patient names + MRNs but not full DOB
--   ADMIN_ROLE          — full access (auditing only; never used for analytics)
-- DBT_ROLE is operational, used by dbt + Airflow to BUILD models, but does
-- not have masking-policy bypass.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DBT_ROLE
    COMMENT = 'Operational role for dbt + Airflow. Build-time only.';
CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Read-only on de-identified marts; no PHI access.';
CREATE ROLE IF NOT EXISTS CLINICIAN_ROLE
    COMMENT = 'Read access on patient-level records (name + MRN visible, full DOB masked to year-only).';
CREATE ROLE IF NOT EXISTS PHI_ADMIN_ROLE
    COMMENT = 'Full PHI access — for audit only.';

GRANT ROLE DBT_ROLE        TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE    TO ROLE SYSADMIN;
GRANT ROLE CLINICIAN_ROLE  TO ROLE SYSADMIN;
GRANT ROLE PHI_ADMIN_ROLE  TO ROLE SYSADMIN;

CREATE USER IF NOT EXISTS DBT_USER
    PASSWORD = 'ChangeMe_BeforeRunning_123!'
    DEFAULT_ROLE = DBT_ROLE
    DEFAULT_WAREHOUSE = DBT_WH_XS
    DEFAULT_NAMESPACE = HEALTHCARE_DB.RAW
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE DBT_ROLE TO USER DBT_USER;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE DBT_WH_XS  TO ROLE DBT_ROLE;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE LOAD_WH_XS TO ROLE DBT_ROLE;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE EXPT_WH_S  TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE DBT_WH_XS TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE DBT_WH_XS TO ROLE CLINICIAN_ROLE;

GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE CLINICIAN_ROLE;
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE PHI_ADMIN_ROLE;

GRANT CREATE SCHEMA ON DATABASE HEALTHCARE_DB TO ROLE DBT_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE FUNCTION, CREATE PROCEDURE, CREATE PIPE, CREATE STREAM, CREATE TASK,
      CREATE MASKING POLICY, CREATE ROW ACCESS POLICY
    ON SCHEMA HEALTHCARE_DB.RAW TO ROLE DBT_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION, CREATE PROCEDURE
    ON SCHEMA HEALTHCARE_DB.STAGING TO ROLE DBT_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION, CREATE PROCEDURE
    ON SCHEMA HEALTHCARE_DB.INTERMEDIATE TO ROLE DBT_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE FUNCTION, CREATE PROCEDURE,
      CREATE MATERIALIZED VIEW
    ON SCHEMA HEALTHCARE_DB.MARTS TO ROLE DBT_ROLE;

GRANT USAGE, CREATE MASKING POLICY, CREATE ROW ACCESS POLICY, CREATE VIEW
    ON SCHEMA HEALTHCARE_DB.GOVERNANCE TO ROLE DBT_ROLE;

GRANT USAGE, CREATE VIEW, CREATE TABLE
    ON SCHEMA HEALTHCARE_DB.BASELINE TO ROLE DBT_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA HEALTHCARE_DB.META TO ROLE DBT_ROLE;

GRANT USAGE, CREATE TABLE
    ON SCHEMA HEALTHCARE_DB.SNAPSHOTS TO ROLE DBT_ROLE;

-- Read access for analyst + clinician on MARTS (with masking policies)
GRANT USAGE ON SCHEMA HEALTHCARE_DB.MARTS TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.MARTS TO ROLE CLINICIAN_ROLE;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.MARTS TO ROLE PHI_ADMIN_ROLE;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.BASELINE TO ROLE ANALYST_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_DB.MARTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA HEALTHCARE_DB.MARTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_DB.MARTS TO ROLE CLINICIAN_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA HEALTHCARE_DB.MARTS TO ROLE CLINICIAN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_DB.MARTS TO ROLE PHI_ADMIN_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA HEALTHCARE_DB.MARTS TO ROLE PHI_ADMIN_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA HEALTHCARE_DB.BASELINE TO ROLE ANALYST_ROLE;

-- DBT must own its built tables to apply policies
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE HEALTHCARE_DB TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE HEALTHCARE_DB TO ROLE DBT_ROLE;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DBT_ROLE;

SHOW GRANTS TO ROLE DBT_ROLE;
SHOW GRANTS TO ROLE ANALYST_ROLE;
SHOW GRANTS TO ROLE CLINICIAN_ROLE;
SHOW GRANTS TO ROLE PHI_ADMIN_ROLE;
