-- =====================================================================
-- 03_setup_resource_monitors.sql
-- =====================================================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR PROJECT_MONTHLY_CAP
    WITH CREDIT_QUOTA = 50
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75  PERCENT DO NOTIFY
        ON 90  PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND
        ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE DBT_WH_XS  SET RESOURCE_MONITOR = PROJECT_MONTHLY_CAP;
ALTER WAREHOUSE LOAD_WH_XS SET RESOURCE_MONITOR = PROJECT_MONTHLY_CAP;
ALTER WAREHOUSE EXPT_WH_S  SET RESOURCE_MONITOR = PROJECT_MONTHLY_CAP;

SHOW RESOURCE MONITORS;
